! -------------------------------------------------------------------------
!
SUBROUTINE AOT(EPS_T,EPS_B,TETAD_SOIL)
!
! -------------------------------------------------------------------------
!
!     CODE ORIGINALLY OBTAINED IN MATLAB FROM PULLIAINEN
!
!     FUNCTION FOR CALCULATING THE ANGLE OF TRANSMISSION
!     IN THE CASE OF A PLANE BOUNDARY BETWEEN TWO
!     MEDIAS WITH COMPLEX PERMITTIVITIES
!     K. TIGERSTEDT/97
!
!   INPUT PARAMETERS:
!     EPS_T = TOP LAYER EPSILON_R [COMPLEX],
!     EPS_B = BOTTOM LAYER EPSILON_R [COMPLEX]
!     THETAD = INCIDENCE ANGLE [DEG]
!   OUTPUT:
!     KSID   = TRANSMISSION ANGLE IN BOTTOM LAYER [DEG]
!
!   VERSION HISTORY:
!      1.0    KT ?.?.97
!      2.0    MD 1 APR 05 TRANSLATED TO FORTRAN FROM MATLAB

IMPLICIT NONE

REAL(8), INTENT(IN) :: EPS_T,EPS_B
REAL(8), INTENT(INOUT) :: TETAD_SOIL
REAL(8) THETA,KSI,PI
COMPLEX(8) NUMERATOR,DENOMINATOR

PI=3.14159d0
THETA=TETAD_SOIL/180d0*PI
NUMERATOR=EPS_T**0.5d0*SIN(THETA)
DENOMINATOR=(EPS_B-EPS_T*(1-COS(THETA)**2d0))**0.5d0

!KSI=ATAN(REAL(NUMERATOR)/REAL(DENOMINATOR))
!TETAD_SOIL=KSI/PI*180

KSI=ATAN(Real(NUMERATOR/DENOMINATOR))
TETAD_SOIL=REAL(KSI/PI*180d0)


END SUBROUTINE AOT
