! -------------------------------------------------------------------------
!
SUBROUTINE GAMMAV(EPSS,THETA,GAMMAV_VAR)
!
! -------------------------------------------------------------------------
!
!     CODE ORIGINALLY OBTAINED IN MATLAB FROM PULLIAINEN
!
!    VERSION HISTORY:
!      1.0    JPK 5.12.89
!      1.1    JP 17.03.93
!      2.0    MD 1 APR 05 TRANSLATED TO FORTRAN FROM MATLAB
!
!     NOTE: ADDITIONAL FINNISH COMMENTS NOT COPIED HERE

IMPLICIT NONE

REAL(8),INTENT(IN) :: THETA
COMPLEX(8),INTENT(IN) :: EPSS
REAL(8),INTENT(OUT) :: GAMMAV_VAR
REAL(8) THETA_RAD,PI,COSTHETA
COMPLEX(8) NELIO

PI=3.14159d0
THETA_RAD=THETA/180d0*PI
COSTHETA=COS(THETA_RAD)
NELIO=SQRT(EPSS-SIN(THETA_RAD)**2d0)
GAMMAV_VAR=(ABS((EPSS*COSTHETA-NELIO)/(EPSS*COSTHETA+NELIO)))**2d0

END SUBROUTINE GAMMAV
