! -------------------------------------------------------------------------
!
SUBROUTINE POLDER(VFI,A,EICE,EPSI,EPSEFF,NUM)
!
! -------------------------------------------------------------------------
!  WRITTEN BY MIKE, 1 APRIL 05
!  SOLVES (1) THROUGH (5) IN MATZLER, 1996 IN IEEE
!  IMPLEMENTS NEWTON-RAPHSON ITERATION TECHNIQUE IN ORDER TO SOLVE THE RESULT
!  OF SUBSTITUTING EQUATIONS (4) AND (5) INTO (3),THEN (3) INTO (1) AND SOLVING.
!  FOR DOCUMENTATION, SEE REPORT "SOLVING FOR EEFF.SXW" UNDER REPORTS/MEMLS
!  FOLDER.
!
!  INPUTS: V - VOLUME FRACTION OF ICE
!          A - DEPOLARIZATION FACTOR
!          EICE - ICE PERMITTIVITY
!          EPSI - DRY SNOW PERMITTIVITY
!  OUTPUT: EPSEFF - EFFECITVE ICE PERMITTIVITY

IMPLICIT NONE

INTEGER, INTENT(IN) :: NUM
REAL(8), INTENT(IN) :: VFI(NUM),A(NUM),EICE,EPSI(NUM)
REAL(8), INTENT(OUT) :: EPSEFF(NUM)
REAL(8) EPS,X,F,U1,V1,U2,V2,B,T,DBDX,DTDX,DFDX,DELTAX
INTEGER I,K

EPS=0.001d0
DO I=1,NUM
!X=1-EPSI(I)    !X0, INITIAL GUESS
X=EPSI(I)-1    !Revised Jinmei!
F=EPS*10d0       !DUMMY VALUE FOR FIRST GUESS
K=1            !ITERATION COUNTER
DO
K=K+1

U1=2d0*(1d0+(1d0-A(I))*X)
V1=1d0+(1d0-A(I))*X+A(I)*(EICE-1d0)
U2=1d0+2d0*A(I)*X
V2=1d0+2d0*A(I)*X+(1d0-2d0*A(I))*(EICE-1d0)

B=3d0-VFI(I)*(EICE-1d0)*(2d0*A(I)/V1+(1d0-2d0*A(I))/V2) !Demoninator of eps_eff-eps_1 in eq(22), where eps_1=1

T=VFI(I)*(EICE-1d0)*(U1/V1+U2/V2)               !Numerator of eps_eff-eps_1 in eq(22)

DBDX=2d0*A(I)*VFI(I)*(EICE-1d0)*((1d0-A(I))/V1**2d0+(1d0-2d0*A(I))/V2**2d0)
DTDX=DBDX*(EICE-1d0)
!DFDX=1-(B*DTDX-T*DBDX)/B**2   !Jinmei revised, I think it needs to be revised accordingly
DFDX=(B*DTDX-T*DBDX)/B**2d0

DELTAX=-1*F/DFDX
X=X+DELTAX

F=X-T/B
IF (ABS(F)<EPS) EXIT    ! TEST WHETHER WE ARE CLOSE ENOUGH TO ZERO
END DO
EPSEFF(I)=X+1
END DO

END SUBROUTINE POLDER
