! -------------------------------------------------------------------------
!
SUBROUTINE SLRED(NUM,ROI,EPSI,EPSII,TEI,SIH,SIV,DI,DEI,TI,PCI,WI,GAI,FREQ, &
RNUM,XROI,XEPSI,XEPSII,XTEI,XSIH,XSIV,XDI,XDEI,XTI,XPCI,XWI,XGAI)
!
! -------------------------------------------------------------------------
!
!   LOCATES AND TREATS COHERENT LAYERS IN A SNOWPACK
!     SEE TECHNOTE 11
!
!   [RNUM,RROI,REPSI,REPSII,RTEI,RSIH,RSIV,RDI,RDEI,RTI,RPCI,RWI,RGAI]=
!       SLRED(NUM,ROI,EPSI,EPSII,TEI,SIH,SIV,DI,DEI,TI,PCI,FREQ,WI,GAI)
!       NUM:  INDEX OF THE LAYER IN THE ORIGINAL SNOWPACK
!       ROI:  DENSITY [G/CM^3]
!       EPSI:
!       EPSII:
!       TEI:  LOCAL INCIDENCE ANGLE
!       SIH:  LAYER REFLECTIVITY AT H POL
!       SIV:  LAYER REFLECTIVITY AT V POL
!       DI:   LAYER THICKNESS
!       DEI:  LOCAL PATH LENGTH [M]
!       TI:   PHYSICAL SNOW TEMPERATURE [K]
!       PCI:  CORRELATION LENGTH [MM]
!       WI:   WETNESS
!       GAI:  ABSORPTION COEFFICIENT
!       FREQ: FREQUENCY
!
!      1.0    WI 21.8.95
!      2.0    WI 13.8.98  COMPLETELY REWRITTEN
!      3.0    MD 1  APR 05 STRIPPED DOWN TO ONLY CHECK FOR COHERENT LAYERS -MD
!      3.1    MD 18 APR 05 FUNCTIONALITY ADDED TO DEAL WITH COHERENT LAYERS,
!                            SO LONG AS THERE ARE NOT SUCCESSIVE LAYERS
!      3.2    MD 04 NOV 05 FUNCTIONALITY ADDED TO DEAL WITH SUCCESSIVE
!                            COHERENT LAYERS FOR THREE LAYERS
!      3.3    MD 12 NOV 05 CHANGED TO DYNAMICALLY ALLOCATE ALL LOCALS
!      4.0    JG 10 DEC 10 ADDED FUNCTIONALITY FROM MATLAB FOR ARBITRARY
!                            NUMBER OF LAYERS
!      4.1    MD 08 APR 11 SLIGHT TWEAKS TO JG'S CODE
!
!   USES:
!       FRESNELRC
!
!   COPYRIGHT (C) 1997 BY THE INSTITUTE OF APPLIED PHYSICS,
!   UNIVERSITY OF BERN, SWITZERLAND

IMPLICIT NONE

INTEGER,INTENT(IN) :: NUM
REAL(8),INTENT(INOUT) :: ROI(NUM),EPSI(NUM),EPSII(NUM),TEI(NUM+1),SIH(NUM),&
SIV(NUM),DI(NUM),DEI(NUM),TI(NUM),PCI(NUM),WI(NUM),GAI(NUM)
REAL(8),INTENT(IN) :: FREQ
REAL(8),INTENT(OUT) :: XROI(NUM),XEPSI(NUM),XEPSII(NUM),XTEI(NUM+1),XSIH(NUM),&
XSIV(NUM),XDI(NUM),XDEI(NUM),XTI(NUM),XPCI(NUM),XWI(NUM),XGAI(NUM)
INTEGER, INTENT(OUT) :: RNUM
INTEGER, DIMENSION(:), ALLOCATABLE :: I,A
REAL(8) CC,PI,FIC,FC,THETA
REAL(8),DIMENSION(:),ALLOCATABLE ::  NS,FI,X
INTEGER J,NTHIN,PL,SC,SCMAX,ML,MLO,M,K,NAEQ0,NAEQ1,tnum
REAL(8) FITOT
REAL(8),DIMENSION(:),ALLOCATABLE :: TROI,TEPSI,TEPSII,TTEI,FITV,&
TSIH,TSIV,TDI,TDEI,TTI,TPCI,TWI,TGAI,TNS,TFI,EPSI_AUG,FH,FV
REAL(8),DIMENSION(:),ALLOCATABLE :: T2ROI,T2EPSI,T2EPSII,T2TEI,&
T2DI,T2DEI,T2TI,T2PCI,T2WI,T2GAI,T2NS,T2FI
INTEGER TAL
LOGICAL,DIMENSION(:),ALLOCATABLE :: MASK

!integer,intent(in) :: pixel,replicate,rank,meas

ALLOCATE(NS(NUM),FI(NUM), X(NUM))

! IN GENERAL, WE FIRST TEST TO SEE IF THERE ARE ANY COHERENT LAYERS.  IF NOT,
!   WE SKIP TO CASE 2, OTHERWISE, WE HAVE CASE 1.  IN CASE 1, THE FIRST STEP IS
!   TO TREAT THE EFFECT OF SUCCESSIVE COHERENT SNOWPACK LAYERS BY COMBINING
!   THESE INTO A SINGLE LAYER. IF THERE ARE NO SUCCESSIVE COHERENT LAYERS,
!   WE SKIP TO STEP 2; REGARDLESS, THE ARRAYS WITH THE T- PREFIX ARE DEFINED
!   BEFORE STEP 2.  IN STEP 2, THE EFFECT OF ISOLATED COHERENT LAYERS IS
!   DEALT WITH BY INCORPORATING THE EFFECT OF EACH COHERENT LAYER INTO THE
!   INTER-LAYER REFLECTIVITIES.

! CONSTANTS
CC=0.299793d0
PI=3.14159d0
FIC=4d0*PI*FREQ/CC
FC=4.712d0

! COMPUTE FI IN ORDER TO CHECK ON COHERENT LAYERS
THETA=TEI(NUM+1)
NS=EPSI**0.5d0
FI=FIC*DI*NS*COS(TEI(1:NUM))

! COUNT THE THIN LAYERS
NTHIN=0
DO J=1,NUM
    IF (FI(J)<FC) THEN
        NTHIN=NTHIN+1
    END IF
END DO

! ALLOCATE THE I ARRAY, WHICH CONTAINS THE INDECES OF THE THIN LAYERS
ALLOCATE(I(1:NTHIN),A(NUM))

! DEFINE THE I AND A ARRAYS.  THE A ARRAY HAS A VALUE OF 1 FOR THIN
!   LAYERS AND 0 OTHERWISE
K=0
DO J=1,NUM
    IF (FI(J)<FC) THEN
        K=K+1
        I(K)=J
        A(J)=1
    ELSE
        A(J)=0
    END IF
END DO


! THE BOTTOM LAYER IS ALWAYS ASSUMED NONCOHERENT
A(1)=0


! CHECK TO SEE IF WE HAVE ANY COHERENT LAYERS TO TREAT.  IF NOT, ALLOCATE
!   THE REPLACEMENT ARRAYS (WITH THE 'R' PREFIX) WITH A SIZE OF THE ORIGINAL
!   NUMBER OF LAYERS, THEN DEFINE THOSE ARRAYS BASED ON THE ORIGINAL VALUES
! IF THERE IS ONLY ONE LAYER, IT IS ASSUMED TO BE NONCOHERENT, SO THE ORIGINAL
!   NUMBER OF LAYERS IS ASSIGNED TO RNUM AND THE OUTPUTS SET TO THE INPUTS.

IF (NTHIN>0.AND.NUM.GT.1) THEN
! CASE 1: TREAT COHERENT LAYERS IN THE SNOWPACK
! 1) IDENTIFY SUCCESSIVE COHERENT LAYERS AND MARK THE PACKS FROM 2,3...SCMAX
    PL=0
    SC=1
    SCMAX=0
    ML=0
    MLO=0

    DO M=2,NUM
        IF (A(M)==1 .AND. PL==1) THEN
            IF(ML==0)THEN
                SC=SC+1
                ML=1
                A(M-1)=SC
            END IF

            A(M)=SC
            SCMAX=SC
        ELSE
            IF (PL==1) THEN
                PL=0
            ELSE
                IF(A(M)==1)THEN
                    PL=1
                    ML=0
                END IF
            END IF
        END IF
    END DO

    !JG'S CODE TO ALLOW SUCCESSIVE COHERENT LAYERS BEGINS HERE. MD, 4/8/2011
    IF (SCMAX>0) THEN
        ! COMBINE SUCCESSIVE COHERENT LAYERS BY WEIGHTING WITH THE PHASE
        ! COPY ARRAYS TO TEMPORARIES FOR SIMPLICITY OF CODE
        ALLOCATE(T2DI(NUM),T2DEI(NUM),T2ROI(NUM),T2TI(NUM),T2WI(NUM),T2PCI(NUM),&
        T2NS(NUM),T2GAI(NUM),T2EPSI(NUM),T2EPSII(NUM),T2TEI(NUM+1),T2FI(NUM))
        ALLOCATE(MASK(NUM),FITV(NUM))
        T2DI=DI
        T2DEI=DEI
        T2ROI=ROI
        T2TI=TI
        T2WI=WI
        T2PCI=PCI
        T2NS=NS
        T2GAI=GAI
        T2EPSI=EPSI
        T2EPSII=EPSII
        T2TEI=TEI
        T2FI=FI
        ! COMBINE LAYERS
        DO M=2,SCMAX
            MASK=(A==M)
            FITOT=SUM(FI,1,MASK)
            FITV=FI/FITOT        ! WILL USE ONLY ELEMENTS CORRESPONDING TO MASK
            ! FIND MAXIMUM INDEX FOR WHICH A==M
            TAL=NUM
            DO WHILE (.NOT. MASK(TAL))
                TAL=TAL-1
            END DO
            ! THIS IS NOT EFFICIENT, JUST A QUICK AND SIMPLE TRANSLATION FROM MATLAB
            T2DI(TAL)=SUM(DI,1,MASK)
            T2DEI(TAL)=SUM(DEI,1,MASK)
            T2ROI(TAL)=SUM(ROI*FITV,1,MASK)
            T2TI(TAL)=SUM(TI*FITV,1,MASK)
            T2WI(TAL)=SUM(WI*FITV,1,MASK)
            T2PCI(TAL)=SUM(PCI*FITV,1,MASK)
            T2NS(TAL)=SUM(NS*FITV,1,MASK)
            T2GAI(TAL)=SUM(GAI*FITV,1,MASK)
            T2EPSI(TAL)=SUM(EPSI*FITV,1,MASK)
            T2EPSII(TAL)=SUM(EPSII*FITV,1,MASK)
            T2TEI(TAL)=SUM(TEI(1:NUM)*FITV,1,MASK)
            T2FI(TAL)=FITOT
            A(TAL)=1
        ENDDO

        ! REMOVE REDUNDANT LAYERS THAT WERE COMBINED WITH SUCCESIVE LAYERS
        ! SAVE NEW ARRAYS IN Tx ARRAYS
        MASK=(A<2)
        TNUM=COUNT(MASK)
        !    ALLOCATE(TDI(TNUM),TDEI(TNUM),TROI(TNUM),TTI(TNUM),TWI(TNUM),TPCI(TNUM),TNS(TNUM),& !Mike removing the duplicate TNS() allocation
        ALLOCATE(TDI(TNUM),TDEI(TNUM),TROI(TNUM),TTI(TNUM),TWI(TNUM),TPCI(TNUM),&
        TNS(TNUM),TGAI(TNUM),TEPSI(TNUM),TEPSII(TNUM),TTEI(TNUM+1),TFI(TNUM))
        TDI=PACK(T2DI,MASK)
        TDEI=PACK(T2DEI,MASK)
        TROI=PACK(T2ROI,MASK)
        TTI=PACK(T2TI,MASK)
        TWI=PACK(T2WI,MASK)
        TPCI=PACK(T2PCI,MASK)
        TNS=PACK(T2NS,MASK)
        TGAI=PACK(T2GAI,MASK)
        TEPSI=PACK(T2EPSI,MASK)
        TEPSII=PACK(T2EPSII,MASK)
        TTEI(1:TNUM)=PACK(T2TEI(1:NUM),MASK)
        !    TTEI(TNUM+1)=NUM+1     !JG'S LINE
        TTEI(TNUM+1)=TEI(NUM+1) !MD's EDIT, 4/8/11
        TFI=PACK(T2FI,MASK)
        DEALLOCATE(T2DI,T2DEI,T2ROI,T2TI,T2WI,T2PCI,T2NS,T2GAI,T2EPSI,T2EPSII,&
            T2TEI,T2FI)
        DEALLOCATE(MASK,FITV)
    ELSE
        !IF THERE ARE NO SUCCESSIVE COHERENT LAYERS, I WILL MAP THE x ARRAYS TO
        !  THE Tx ARRAYS...
        ALLOCATE(TDI(NUM),TDEI(NUM),TROI(NUM),TTI(NUM),TWI(NUM),TPCI(NUM),&
        TNS(NUM),TGAI(NUM),TEPSI(NUM),TEPSII(NUM),TTEI(NUM+1),TFI(NUM))
        TDI=DI
        TDEI=DEI
        TROI=ROI
        TTI=TI
        TWI=WI
        TPCI=PCI
        TNS=NS
        TGAI=GAI
        TEPSI=EPSI
        TEPSII=EPSII
        TTEI=TEI
        TFI=FI
        TNUM=NUM
    ENDIF
    DEALLOCATE(I,A) ! THIS WAS ADDED BY MD, 4/8/11. JG HAD REMOVED IT.
    ! IT NEEDS TO BE IN SINCE A,I ARE REALLOCATED BELOW.

    ! 2) DEAL WITH ISOLATED COHERENT LAYERS BY COMBINING THESE LAYERS' EFFECTS
    ! INTO THE INTER-LAYER REFLECTIVITIES

    ! COUNT THE THIN LAYERS AFTER REMOVAL OF SUCCESSIVE COHERENT LAYERS.

    ! NOTE THAT THE BOTTOM LAYER IS ALWAYS ASSUMED NON-COHERENT: DON'T COUNT IT.
    ! THIS CHANGE MADE BY MD, 4/8/11
    NTHIN=0
    DO J=2,TNUM
        IF (TFI(J)<FC ) THEN
            NTHIN=NTHIN+1
        END IF
    END DO

    ! ALLOCATE THE A ARRAY WHICH MARKS COHERENT LAYERS; THE I ARRAY SWITCHES
    !   BETWEEN MARKING INDECES OF COHERENT AND NONCOHERENT LAYERS.  THE GOAL
    !   IS TO CALCULATE THE INTERFACE REFLECTIVITIES.

    !  ALLOCATE(I(NTHIN),A(TNUM)) !THIS CHANGE BY MD, 4/8/11: I SHOULD BE SAME
    !    SIZE AS A. IT IS NOT USED, ANYWAY, HERE, AND IS DEALLOCATED, SO SHOULD
    !    PROBABLY JUST REMOVE IN THE FUTURE.
    ALLOCATE(I(TNUM),A(TNUM))

    ! REDEFINE THE I AND A ARRAYS.  THE A ARRAY HAS A VALUE OF 1 FOR THIN
    !   LAYERS AND 0 OTHERWISE, NOW THAT THERE ARE NO SUCCESSIVE COHERENT LAYERS
    K=0
    DO J=1,TNUM
        IF (TFI(J)<FC) THEN
            K=K+1
            I(K)=J
            A(J)=1
        ELSE
            A(J)=0
        END IF
    END DO
    ! THE BOTTOM LAYER IS ALWAYS ASSUMED NONCOHERENT
    A(1)=0
    DEALLOCATE(I) !I IS NOT USED NOW

    !  FIND THE VALUES OF A EQUAL TO ZERO, SAVE THE INDECES TO I
    NAEQ0=0
    DO J=1,TNUM
        IF (A(J)==0) THEN
            NAEQ0=NAEQ0+1
        END IF
    END DO
    ALLOCATE(I(NAEQ0))

    K=0
    DO J=1,TNUM
        IF (A(J)==0) THEN
            K=K+1
            I(K)=J
        END IF
    END DO

    ! CALCULATE INTERFACE REFLECTION COEFFICIENTS
    ALLOCATE(EPSI_AUG(TNUM+1),FH(TNUM),FV(TNUM))
    EPSI_AUG(1:TNUM)=TEPSI
    EPSI_AUG(TNUM+1)=1.0d0

    CALL FRESNELRC(TTEI,EPSI_AUG,FH,FV,TNUM)

    ! FOR LAYERS OF TYPE 0 SHI = FH^2
    ALLOCATE(TSIH(TNUM),TSIV(TNUM))
    DO J=1,NAEQ0
        TSIH(I(J))=FH(I(J))**2d0
        TSIV(I(J))=FV(I(J))**2d0
    END DO

    IF(NTHIN.EQ.0)THEN
        ! THERE ARE NO MORE COHERENT LAYERS AFTER REMOVAL OF SUCCESSIVE COHERENT
        ! LAYERS SO SET THE OUTPUT ARRAYS EQUAL TO CURRENT Tx ARRAYS
        RNUM=TNUM
        XROI(1:RNUM)=TROI
        XEPSI(1:RNUM)=TEPSI
        XEPSII(1:RNUM)=TEPSII
        XTEI(1:RNUM+1)=TTEI
        XSIH(1:RNUM)=TSIH
        XSIV(1:RNUM)=TSIV
        XDI(1:RNUM)=TDI
        XDEI(1:RNUM)=TDEI
        XTI(1:RNUM)=TTI
        XPCI(1:RNUM)=TPCI
        XWI(1:RNUM)=TWI
        XGAI(1:RNUM)=TGAI
    ELSE
    ! IF THERE ARE STILL COHERENT LAYERS AFTER REMOVAL OF SUCCESSIVE COHERENT
    ! LAYERS, THEN DEAL WITH THESE.  DO A REDUCTION ON LAYERS OF TYPE 0
    !   (COHERENT LAYER EFFECTS ARE TAKEN INTO ACCOUNT IN THE LAYER
    !   REFLECTIVITIES)

    !  FIND THE NUMBER OF VALUES OF A EQUAL TO ONE

        DEALLOCATE(I)
        NAEQ1=0
        DO J=1,TNUM
            IF (A(J)==1) THEN
                NAEQ1=NAEQ1+1
            END IF
        END DO
        ALLOCATE(I(1:NAEQ1))

        !  FIND THE VALUES OF A EQUAL TO ONE
        K=0
        DO J=1,TNUM
            IF (A(J)==1) THEN
                K=K+1
                I(K)=J
            END IF
        END DO

        !COMPUTE NEW INTERFACE REFLECTIVITIES
        X=0 !INITIALIZE VARIABLES
        !    XSIH=TSIH
        !    XSIV=TSIV
        DO J=1,NAEQ1
            X(I(J))=2*FH(I(J))*FH(I(J)-1)*COS(FI(I(J)))
            TSIH(I(J)-1)=(FH(I(J))**2+FH(I(J)-1)**2+X(I(J)))/&
            (1+FH(I(J))**2*FH(I(J)-1)**2+X(I(J)))
            X(I(J))=2*FV(I(J))*FV(I(J)-1)*COS(FI(I(J)))
            TSIV(I(J)-1)=(FV(I(J))**2+FV(I(J)-1)**2+X(I(J)))/&
            (1+FV(I(J))**2*FV(I(J)-1)**2+X(I(J)))
        END DO

        !  FIND THE NUMBER OF VALUES OF A EQUAL TO ZERO
        DEALLOCATE(I)
        NAEQ0=0
        DO J=1,TNUM
            IF (A(J)==0) THEN
                NAEQ0=NAEQ0+1
            END IF
        END DO
        ALLOCATE(I(NAEQ0))

        !  FIND THE VALUES OF A EQUAL TO ZERO
        K=0
        DO J=1,TNUM
            IF (A(J)==0) THEN
                K=K+1
                I(K)=J
            END IF
        END DO

        !  DEFINE OUTPUT VARIABLES BASED ON I ARRAY
        DO J=1,NAEQ0
        !      XROI(J)=ROI(I(J))
        !      XTEI(J)=TEI(I(J))
        !      XDI(J)=DI(I(J))
        !      XTI(J)=TI(I(J))
        !      XPCI(J)=PCI(I(J))
        !      XWI(J)=WI(I(J))
        !      XGAI(J)=GAI(I(J))
            XROI(J)=TROI(I(J))
            XTEI(J)=TTEI(I(J))
            XDI(J)=TDI(I(J))
            XTI(J)=TTI(I(J))
            XPCI(J)=TPCI(I(J))
            XWI(J)=TWI(I(J))
            XGAI(J)=TGAI(I(J))

        !      XSIH(J)=XSIH(I(J))
        !      XSIV(J)=XSIV(I(J))

            XSIH(J)=TSIH(I(J))
            XSIV(J)=TSIV(I(J))

        !      XEPSI(J)=EPSI(I(J))
        !      XEPSII(J)=EPSII(I(J))
        !      XDEI(J)=DEI(I(J))
            XEPSI(J)=TEPSI(I(J))
            XEPSII(J)=TEPSII(I(J))
            XDEI(J)=TDEI(I(J))
        END DO

        RNUM=TNUM-NTHIN
        XTEI(RNUM+1)=THETA
    END IF

    DEALLOCATE(TDI,TDEI,TROI,TTI,TWI,TPCI,TNS,TGAI,TEPSI,TEPSII,TTEI,TFI,&
    TSIH,TSIV)
    DEALLOCATE(EPSI_AUG,FH,FV) !Jinmei added Dec23,2015


ELSE
    ! THERE ARE NO COHERENT LAYERS (OR ONLY ONE LAYER), SO SET THE OUTPUT
    ! ARRAYS EQUAL TO THE INPUT ARRAYS
    RNUM=NUM
    XROI=ROI
    XEPSI=EPSI
    XEPSII=EPSII
    XTEI=TEI
    XSIH=SIH
    XSIV=SIV
    XDI=DI
    XDEI=DEI
    XTI=TI
    XPCI=PCI
    XWI=WI
    XGAI=GAI
END IF


DEALLOCATE(NS,FI,X)
DEALLOCATE(I,A)  !Jinmei Added Dec23,2015

END SUBROUTINE SLRED
